#!/usr/bin/env python3
"""Write Sources/Bytemeter/DashboardFonts.swift from the fonts in Resources/Fonts.

The dashboard carries its typefaces inside the page as base64 woff2, so it
renders the same with the network off and fetches nothing. The Swift file is
committed, so `swift build` never needs Python. Run this after changing a font.

    python3 Scripts/make_fonts.py           write the Swift file
    python3 Scripts/make_fonts.py --check   change nothing; exit 1 if the
                                            committed file does not match the fonts
"""
import base64
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONT_DIR = ROOT / "Resources" / "Fonts"
OUT = ROOT / "Sources" / "Bytemeter" / "DashboardFonts.swift"

# Family, file, the weight range the file covers, and its licence. Both are
# variable fonts; the range is the file's own weight axis.
FONTS = (
    ("Fraunces", "fraunces.woff2", "100 900", "OFL-Fraunces.txt"),
    ("Inter Tight", "inter-tight.woff2", "100 900", "OFL-InterTight.txt"),
)

# Base64 characters per line of Swift, so the file stays readable in an
# editor and a diff. Each line ends in a backslash, which in a Swift
# multi-line string joins it to the next, so the CSS gets one unbroken value.
WRAP = 120
INDENT = " " * 8


def fail(message: str) -> None:
    print(f"make_fonts: {message}", file=sys.stderr)
    sys.exit(1)


def render() -> str:
    files = []
    rules = []
    for family, name, weights, licence in FONTS:
        path = FONT_DIR / name
        try:
            raw = path.read_bytes()
        except OSError:
            fail(f"{path} is missing")
        if raw[:4] != b"wOF2":
            fail(f"{path} is not a woff2 file")
        files.append((name, len(raw), hashlib.sha256(raw).hexdigest(), licence))
        b64 = base64.b64encode(raw).decode("ascii")
        lines = [f"@font-face{{font-family:'{family}';font-style:normal;font-weight:{weights};"
                 f"font-display:block;\\",
                 "src:url(data:font/woff2;base64,\\"]
        lines += [b64[i:i + WRAP] + "\\" for i in range(0, len(b64), WRAP)]
        lines.append(") format('woff2')}")
        rules.append("\n".join(INDENT + line for line in lines))

    out = [
        "// Generated by Scripts/make_fonts.py from Resources/Fonts. Do not edit by",
        "// hand: change a font there, then run python3 Scripts/make_fonts.py.",
        "",
        "/// The dashboard's two typefaces as @font-face rules, each with its woff2",
        "/// file inside as base64, so the page renders the same with the network off",
        "/// and fetches nothing. Both are SIL Open Font License 1.1; the licences sit",
        "/// beside the fonts in Resources/Fonts and travel in the app bundle's",
        "/// Contents/Resources/Fonts.",
        "enum DashboardFonts {",
        "",
        "    /// Each file as it was when this was generated: name, size in bytes,",
        "    /// SHA-256, and its licence file.",
        "    static let files: [(name: String, bytes: Int, sha256: String, licence: String)] = [",
    ]
    out += [f'        ("{n}", {b}, "{s}", "{lic}"),' for n, b, s, lic in files]
    out += [
        "    ]",
        "",
        "    /// The rules, placed at the top of the page's stylesheet.",
        '    static let css = """',
        "\n".join(rules),
        '        """',
        "}",
        "",
    ]
    return "\n".join(out)


def main(argv: list) -> int:
    check = "--check" in argv[1:]
    unknown = [a for a in argv[1:] if a != "--check"]
    if unknown:
        fail(f"unknown option {unknown[0]} (use --check or nothing)")
    text = render()
    if check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT.relative_to(ROOT)} does not match the fonts in "
                  f"{FONT_DIR.relative_to(ROOT)}. Run: python3 Scripts/make_fonts.py", file=sys.stderr)
            return 1
        print(f"{OUT.relative_to(ROOT)} matches the fonts.")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}, {len(text.encode()) // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
